name: "Aura SAST scan"
description: "Scan your code with the Aura Framework"

runs:
  using: "docker"
  image: "docker://rootlug/aura-security:dev"
  args:
    - "scan"
    - "/github/home"
    - "-f"
    - "sarif:///github/home/aura_ci_report.sarif"
    - "-f"
    - "plain"
